---
title: Models
---

```{r load-libraries-data, warning=FALSE, message=FALSE}
library(tidyverse)
library(brms)
library(tidybayes)
library(scales)
library(targets)

# Point to the _targets folder location since this qmd is in a subfolder
tar_config_set(store = here::here('_targets'),
               script = here::here('_targets.R'))

# Load targets
tar_load(ongo)
tar_load(c(m_basic_zoib, m_basic_ologit))
tar_load(m_full_zoib)

ongo <- ongo %>% 
  mutate(province0 = province_count - 1)


ggplot(ongo, aes(x = province_count)) +
  geom_bar()
```

```{r eval=FALSE}
library(ordbetareg)

m_basic_ordbeta <- ordbetareg(province_count ~ work_field_code1,
                              data = ongo)

m_full_ordbeta <- ordbetareg(
  bf(province_count ~ work_field_code1 + local_connect + local_aim + psu_level + (1 | province_code)),
  data = ongo,
  true_bounds = c(1, 32),
  extra_prior = priors,
  chains = 4
)

priors <- c(prior(student_t(3, 0, 1.5), class = b, coef = "*"))

priors <- set_prior("normal(0,5)",class="b") + 
  prior(constant(0),class="b",coef="Intercept") +
  prior_string("target += normal_lpdf((cutzero + exp(cutone)) - cutzero|0,3) + cutone",check=F) +
  set_prior("exponential(.1)",class="phi")

m_full_ordbeta1 <- brm(
  bf(province_count ~ 0 + Intercept + work_field_code1 + local_connect + local_aim + psu_level + (1 | province_code)),
  data = ongo,
  prior = priors,
  family = ord_beta_reg,
  stanvars=stanvars, backend = "cmdstanr")

prior_summary(m_full_ordbeta)


conditional_effects(m_full_zoib)
conditional_effects(m_full_ordbeta)

modelr::data_grid()

asdf <- m_full_ordbeta %>% 
  epred_draws(newdata = )

get_prior(
  bf(province_count ~ work_field_code1 + local_connect + local_aim + psu_level + (1 | province_code)),
  data = ongo,
  family = "ord_beta_reg"
)

plots <- pp_check_ordbeta(m_full_ordbeta,
                          ndraws = 100,
                          outcome_label = "Provinces")

plots$continuous

pp_check(m_basic_ordbeta, type = "bars")
```



```{r}
pp_check(m_basic_zoib)
pp_check(m_full_zoib)
```

```{r}
pp_check(m_basic_ologit, type = "bars")
```

```{r}
ongo |> 
  modelr::data_grid(work_field_code1 = unique(work_field_code1)) |> 
  add_epred_draws(m_basic_zoib, ndraws = 1000) |> 
  ungroup() |> 
  drop_na(work_field_code1) |> 
  mutate(work_field_code1 = fct_reorder(work_field_code1, .epred)) |> 
  ggplot(aes(y = work_field_code1, x = .epred, fill = work_field_code1)) +
  stat_halfeye() +
  scale_x_continuous(labels = label_percent()) +
  scale_fill_viridis_d(option = "rocket", end = 0.9) +
  guides(fill = "none") +
  labs(x = "Expected proportion of provinces", y = NULL) +
  theme_minimal()
```

