---
title: "The Implementation of China’s Overseas NGO Law and the Operating Space for International Civil Society"
author:
- name: Meng Ye
  affiliation: Georgia State University
  email: mye2@student.gsu.edu
  orcid: 0000-0002-6552-8338
- name: Andrew Heiss
  affiliation: Georgia State University
  email: aheiss@gsu.edu
  orcid: 0000-0002-3948-3914
format:
  html:
    code-tools: false
    toc: false
---

## Abstract

China’s 2017 Overseas NGO (ONGO) Law is part of a larger global trend of legal restrictions on international nongovernmental organizations (INGOs). However, the effects of this global crackdown on INGOs have been difficult to measure since there is often divergence between the formal de jure regulations and the de facto implementation of these laws. Additionally, the severity and consistency of the enforcement of these laws often depends on the type of services provided by these organizations. In this paper, we explore the effect of China’s ONGO law on INGO operations in the five years since the passage of the law. We test whether and how INGO operational space under the ONGO law is influenced by organizations' issue areas. We argue that the less contensious the issue areas INGOs work in the more likely they are granted greater operational space, measured by the number of provinces they are legally authorized to work in. China provides an excellent setting for examining the phenomenon of closing space civic space, since the 2017 ONGO law hypothetically regulates both claim-making and service-providing NGOs, while the level of ambiguity of the law gives ample room for arbitrary discretion and conflicting attitudes by authorities. We test our argument by analyzing administrative data from 633 registered representative offices of INGOs registered in China between 2017–2021 and test our hypothesis with a multilevel Bayesian model. Our results speak to the broader literature on closing civic space and provide an empirical illustration of the practical effect of NGO restrictions on global civil society.

## Code

All the raw code and data for this paper is available in a [GitHub repository](https://github.com/andrewheiss/compassionate-clam).
