project:
  output-dir: output-ms
  render:
    - appendix.qmd

format:
  # Manuscript-y PDF output
  hikmah-manuscript-pdf:
    cite-method: citeproc
    output-file: "appendix-ms.pdf"
    # Custom fonts
    mainfont: "Linux Libertine O"
    mainfontoptions:
      - "Numbers=Proportional"
      - "Numbers=OldStyle"
    mathfont: "Libertinus Math"

    include-in-header:
      # The \everydisplay thing makes all math blocks use \small font
      text: |
        \usepackage{mathtools}
        \everydisplay\expandafter{\the\everydisplay\small }
        
        \usepackage{xeCJK}
        \setCJKmainfont{Noto Serif SC}

    knitr:
      opts_chunk:
        dev: "cairo_pdf"


  # Manuscript-y Word output
  hikmah-manuscript-odt:
    output-file: "appendix-ms.odt"
    prefer-html: true

    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300
