project:
  title: "Manuscript"
  output-dir: output

  preview: 
    port: 2222
    browser: true
    watch-inputs: false
    navigate: true

  render: 
    - "*.qmd"

format:
  html:
    toc: true
    language: 
      title-block-published: "Latest version"
    shift-heading-level-by: 1
    theme: 
      - zephyr
      - html/custom.scss
    citeproc: false
    filters: 
      - "_extensions/andrewheiss/wordcount/citeproc.lua"
      - "_extensions/andrewheiss/wordcount/wordcount.lua"
    template-partials: 
      - "html/title-metadata.html"
    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300

  # pdf:
  #   documentclass: article
  #   include-in-header:
  #     text: |
  #       \usepackage{mathtools}
  #   knitr:
  #     opts_chunk:
  #       dev: "cairo_pdf"
  
  docx:
    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300
